### PR TITLE
Gracefully handle absence of fastboot

### LINKED ISSUE #376: Make flash-all script check if fastboot exists before checking the version
Currently both the windows and Linux script do not check if fastboot actually exists before checking the version, resulting in errors like:

```
./flash-all.sh: line 17: --version: command not found
./flash-all.sh: line 17: [: -ge: unary operator expected
fastboot too old; please download the latest version at https://developer.android.com/studio/releases/platform-tools.html
```

Not only is it confusing for an end user to understand, it makes the user think that the fastboot version is wrong instead of fastboot not being found in the PATH and doesn't point them to what the error actually is

### PR DESCRIPTION
**Pull request by max-baz**
Fixes https://github.com/GrapheneOS/os_issue_tracker/issues/376

In windows version, writing errors out from powershell looks way too verbose, thus a joined error message.

### CODE REVIEW

**Comment by thestinger** [comment]
Why is a separate error message too verbose for PowerShell? I don't really understand that part.

**Comment by max-baz** [comment]
Before the change:

image

In the current version:

image


If I write errors from PowerShell code like this:

```powershell
Write-Error 'fastboot not found; please download the latest version at https://developer.android.com/studio/releases/platform-tools.html'; ^
```

It looks a bit verbose:

image

I suspected that for this precise reason the current code writes the error from outside of Powershell, instead of from inside:

https://github.com/GrapheneOS/device_common/blob/7322153e3d8aed0403da2401829df7c082d07904/generate-factory-images-common.sh#L214-L215

Hope this clarifies this, what would you like this code to do? 🙂

**Comment by thestinger** [comment]
Why perform this check in the PowerShell code block at all? The only reason it was used for the version check was the difficulty of writing it in the batch script language. Ideally, PowerShell wouldn't be used at all here.

**Comment by max-baz** [comment]
Let me ask the opposite, why not convert this to a PowerShell script entirely? The `grapheneos.org/install` page says "On Windows, use PowerShell rather than the legacy Command Prompt", and as you say batch script language isn't easy to write and I don't think anybody uses it anymore anyway? If I try to search how to check if an executable is in PATH in batch, the first result tells to use `where.exe`, but that executable actually came together with PowerShell I think 🙂

**Comment by thestinger** [comment]
It's not our script. If you want to rewrite it, take that up with AOSP. It's not something we want to maintain downstream.

**Comment by thestinger** [comment]
We want minimal deviations from the upstream code, especially if you're not going to volunteer to do full-time porting for every major version migration on short notice.

**Comment by max-baz** [comment]
Oh I didn't realize. OK what do you want to do with this, should we even touch these scripts in this repo, is it worth deviating from upstream?

**Comment by thestinger** [comment]
A minimal check for the fastboot command.

The version check was already present upstream for Linux. It was missing for Windows, so we added it. Ideally we would have added it without PowerShell but it was too much of a mess.

**Comment by thestinger** [comment]
Look at https://github.com/GrapheneOS/device_common/commits/11 to see our patch set. Our changes to AOSP repositories are maintained as a clean set of rebased patches on top of the latest stable release. It's easy to review our changes. There are no merges or interleaved commits with AOSP.

**Comment by max-baz** [comment]
Gotcha, in this case here is the smallest patch 👍 

Feel free to squash it into https://github.com/GrapheneOS/device_common/commit/a38ef209ea649ac674abe9e51ae00eacc8355309

**Pull request merged**
